const CartActionType = {
  ADD_ITEM: 'ADD_ITEM',
  ADD_ITEM_QUANTITY: 'ADD_ITEM_QUANTITY',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SELECT_ATTRIBUTE: 'SELECT_ATTRIBUTE',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  
}

export default CartActionType;